p_cats/config/routes.rb
Rails.application.routes.draw do
  root to: 'cats#index'
  resources :cats do
    resources :comments
  end
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

p_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

p_cats/app/models/cat.rb
class Cat < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :comments, dependent: :destroy
	validates :name, presence: true, length: {minimum: 3}
end

p_cats/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :cat
end

p_cats/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

p_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  protect_from_forgery with: :exception

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end
end

p_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]
  before_action :authorize


  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    set_cat
    @cat.comments.destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:name, :description, :image)
    end
end

p_cats/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @cat = Cat.find(params[:cat_id])
    @comment = @cat.comments.create(comment_params)
    redirect_to cat_path(@cat)
  end

  def destroy
    @cat = Cat.find(params[:cat_id])
    @comment = @cat.comments.find(params[:id])
    @comment.destroy
    redirect_to cat_path(@cat)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

p_cats/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

p_cats/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new

  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

p_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

p_cats/app/helpers/cats_helper.rb
module CatsHelper
end

p_cats/app/helpers/comments_helper.rb
module CommentsHelper
end

p_cats/app/helpers/sessions_helper.rb
module SessionsHelper
end

p_cats/app/helpers/users_helper.rb
module UsersHelper
end

p_cats/app/views/cats/_form.html.erb
<%= form_with model: cat, local: true do |form| %>
  <% if cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div style="text-align: center">
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cat_name %>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :cat_description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :cat_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
 </div>
<% end %>

p_cats/app/views/cats/edit.html.erb
<h1><%= t(:"Editing Cat") %></h1>

<%= render 'form', cat: @cat %>

<%= button_to t(:'Show'), @cat %> 

p_cats/app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading"><%= t(:"Welcome to the land of cats") %></h1>
          <p class="lead text-muted"><%= t(:"You can upload images of your beloved pets!") %></p>
          <p>
            <a href="#" class="btn btn-common"><%= link_to 'OK', new_cat_path %></a>
          </p>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">


<% @cats.each do |cat| %>
          <div class="jumbotron text-center">
              <div class="card mb-4 box-shadow" >
                <div class="card-body", align="center">
                  <%= image_tag cat.image.thumb.url %>
                  <p class="card-text"><%= cat.name %></p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= link_to 'Show', cat %>|
                      <%= link_to 'Edit', edit_cat_path(cat) %>
                  </div>
                </div>
              </div>
            </div>
          </div>
<% end %>
        </div>
      </div>

    </main>









<!--
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= cat.name %></td>
        <td><%= cat.description %></td>
        <td><%= image_tag cat.image.thumb.url %></td>
        <td><%= link_to 'Show', cat %></td>
        <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
        <td><%= link_to 'Delete', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>  
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %> -->

p_cats/app/views/cats/new.html.erb
<h1>Let's begin!</h1>

<%= render 'form', cat: @cat %>

p_cats/app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>
<div align="center">
<p>
  <strong><h1><%= t(:"Name") %></h1></strong>
  <%= @cat.name %>
</p>

<p>
  <strong><h3><%= t(:"Description") %></h3></strong>
  <%= @cat.description %>
</p>

<p>
  <strong><h3><%= t(:"Image") %></h3></strong>
  <%= image_tag @cat.image.url %>
</p>
</div>

<h2><%= t(:"Comments") %></h2>
<% @cat.comments.each do |comment| %>
  <p>
    <strong><%= t(:"Commenter") %></strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong><%= t(:"Comment") %></strong>
    <%= comment.body %>
  </p>
  <p>
  <%= link_to t(:'Destroy Comment'), [comment.cat, comment],
               method: :delete,
               data: { confirm: t(:'Are you sure?') } %>
  </p>
<% end %>

<h2><%= t(:"Add a comment") %></h2>
<%= form_with(model: [ @cat, @cat.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= text_field_tag :commenter %> 
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= button_to 'Edit', edit_cat_path(@cat) %> 
<%= button_to 'Delete', @cat, method: :delete, data: { confirm: 'Are you sure?' } %> 
<%= button_to 'Back', cats_path %>

p_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t(:"Cats") %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <header>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white"><%= t(:"Features") %></h4>
              <p class="text-muted"><%= link_to t(:'Share your cat!'), new_cat_path %></p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white"><%= t(:"Contacts") %></h4>
              <ul class="list-unstyled">
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 sss0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong><h1><%= link_to  t(:'Cats'), cats_path %></h1></strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>
    <% if current_user %>
      <%= t(:"Signed in as") %> <%= current_user.name %> | <%= link_to t(:"Logout"), '/logout' %>
      <% else %>
    <%= link_to t(:'Login'), '/login' %> | <%= link_to 'Signup', '/signup' %>
    <% end %>
    <li><%= link_to 'Русский', {locale: :ru} %></li>
    <li><%= link_to 'English', {locale: :en} %></li>

    <%= yield %>

  </body>
</html>

p_cats/app/views/users/new.html.erb
<h1><%= t(:"Signup!") %></h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %><br>
  Email: <%= f.text_field :email %><br>
  Password: <%= f.password_field :password %><br>
  Password Confirmation: <%= f.password_field :password_confirmation %><br>
  <%= f.submit "OK" %>

<% end %>